import { CarProps } from "@/types";

export const mockCars: CarProps[] = [

  {
    city_mpg: 30,
    class: "sedan",
    combination_mpg: 34,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 40,
    make: "Toyota",
    model: "Corolla",
    transmission: "a",
    year: 2022,
  },

  {
    city_mpg: 28,
    class: "sedan",
    combination_mpg: 32,
    cylinders: 4,
    displacement: 2.4,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 38,
    make: "Honda",
    model: "Civic",
    transmission: "a",
    year: 2023,
  },

  {
    city_mpg: 25,
    class: "suv",
    combination_mpg: 29,
    cylinders: 4,
    displacement: 2.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 35,
    make: "BMW",
    model: "X5",
    transmission: "a",
    year: 2022,
  },

  {
    city_mpg: 24,
    class: "suv",
    combination_mpg: 28,
    cylinders: 6,
    displacement: 3.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 32,
    make: "Audi",
    model: "Q7",
    transmission: "a",
    year: 2023,
  },

  {
    city_mpg: 26,
    class: "suv",
    combination_mpg: 30,
    cylinders: 4,
    displacement: 2.5,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 36,
    make: "Hyundai",
    model: "Tucson",
    transmission: "a",
    year: 2022,
  },

  {
    city_mpg: 22,
    class: "truck",
    combination_mpg: 25,
    cylinders: 6,
    displacement: 3.5,
    drive: "4wd",
    fuel_type: "gas",
    highway_mpg: 28,
    make: "Ford",
    model: "F-150",
    transmission: "a",
    year: 2023,
  },

  {
    city_mpg: 27,
    class: "sedan",
    combination_mpg: 31,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 37,
    make: "Mercedes",
    model: "C-Class",
    transmission: "a",
    year: 2023,
  },

  {
    city_mpg: 29,
    class: "sedan",
    combination_mpg: 33,
    cylinders: 4,
    displacement: 1.8,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 39,
    make: "Nissan",
    model: "Altima",
    transmission: "a",
    year: 2022,
  },

];